# Azure Pipelines configuration file
trigger:
  branches:
    include:
      - newtest  # Replace 'main' with your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu image for the pipeline

variables:
  NODE_ENV: 'production'
  AZURE_APP_NAME: 'wize'  # Replace with your Azure App Service name
  AZURE_RESOURCE_GROUP: 'wize'  # Replace with your Azure Resource Group name

steps:
  # Step 1: Check out code from the repository
  - task: Checkout@1

  # Step 2: Set up Node.js environment
  - task: UseNode@1
    inputs:
      version: '20.x'  # Use the Node.js version compatible with Next.js

  # Step 3: Install dependencies
  - script: |
      npm install
    displayName: 'Install dependencies'

  # Step 4: Build the Next.js application
  - script: |
      npm run build
    displayName: 'Build Next.js app'

  # Step 5: Deploy to Azure Web App using Azure App Service
  - task: AzureWebApp@1
    inputs:
      appName: 'wize'
      package: '.'  # Deploy the root directory
      deploymentMethod: 'auto'